### ISSUE TITLE
Elementary OS Juno

### ISSUE THREAD

**Issue by core01** [mdh34/elementary-indicators#2]
Hello, thank you for guide!
I have tried to do this with Elementary OS Juno beta 1 but it's doesn't work!
Maybe you have any ideas how to bring back tray in Juno?

Thank you!

**Comment by mdh34** [comment]
This guide was actually specifically written for Juno and beta 1 - I'll have a look to see if it's still working with the latest updates

**Comment by core01** [comment]
@mdh34 I'm sorry, I miss `wingpanel-indicator-ayatana` installation. Indicators works fine with latest updates.

**Comment by mdh34** [comment]
Glad everything is working :)
